# Site settings
title: My 8th Light Blog
email: bnystrom@8thlight.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome, my name is Brian Nystrom. 
  This will be my blog site for the duration of my 8th Light apprenticeship and beyond. 
  Soon enough, there will be more interesting content.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bnystrom.github.io" # the base hostname & protocol for your site
github_username:  nystromb

# Build settings
markdown: kramdown
